### ISSUE TITLE
DeltaSigma from data

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#125]
This is an extension of #114 after this week.

**Comment by m-aguena** [comment]
@aimalz is this issue still valid?

**Comment by aimalz** [comment]
@m-aguena I didn't originally include a sufficient description for me to now answer your question.  On the one hand, we could close the issue with plans to re-open it if someone remembers the context and the issue is still valid.  On the other hand, I don't see code doing this in `clmm/polaraveraging.py` on the master branch (I may have missed something?), and the issue is labeled as an enhancement anyway, meaning it would be appropriate to leave it open.

**Comment by combet** [comment]
**If** I remember correctly... At the moment, `polaraveraging` makes tangential shear profiles `g_t`(i.e. DeltaSigma/Sigma_crit(cosmo) in modeling terms) from the data. I think the question here was whether we should also have the option for `polaraverging` to return DeltaSigma profiles from the data.

**Comment by combet** [comment]
Given that the recent DES papers but also a lot of others perform the mass fit on the `DeltaSigma` profiles rather than on the reduced tangential shear, I think it would be a good thing the provide this functionality in v1. The most straightforward way to tackle this I think,  would be to:
- Add a `compute_deltasigma()` functions into `polaraveraging.py`. It would simply call `compute_shear`, multiply by Sigma_crit and store the results in two new columns of the `galcat` table. `polaravering.py` would now need to `import clmm.modeling` but I remember that it was argued we need to keep data  model/cosmology-independent in CLMM; however, I don't see a way around it if we want to provide DeltaSigma profiles from the data.
- Add a `make_DeltaSigma_profile()` function, that would be the equivalent of `make_shear_profile()`, but for `DeltaSigma`.

What do people think @aimalz, @marina-ricci ? I'll create a `issue/125/deltasigma_from_data` branch so we can start looking into that.

**Comment by pennalima** [comment]
Hi @combet , 
I think it is a good idea. It is going to call the attention of more people.

**Comment by m-aguena** [comment]
@combet correct me if I am mistaken, but `compute_shear` returns reduced shear and not just shear, right? And the convesion happens with shear: `DeltaSigma=gamma_t/SigmaCrit`. I created issue #275  to clarify this.

**Comment by combet** [comment]
I agree, from the model point of view, `DeltaSigma=gamma_t/SigmaCrit`. If the data are simulations (as in cosmoDC2), we may directly have access to the shear. But in 'real life', using shape data only, we don't have access to the convergence and cannot therefore recover the shear from the reduced shear. So I think in that case, all we can do for the data is multiply the **reduced** shear (or more accurately the tangential ellipticity `epsilon_t` - some renaming to be done, see discussion in #248) by `SigmaCrit`. 

See also my comments from #275 and #248 as all this is quite entangled.
