### ISSUE TITLE
Create Model Superclass

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#14]
This will be inherited by profiles (and perhaps things like miscentering, etc.)  We will initially use the lmfit as a template: https://lmfit.github.io/lmfit-py/parameters.html#lmfit.parameter.Parameter

**Comment by cristobal-sifon** [comment]
Because I'm not taking part in the live discussion for the most part, for the time being I outline my suggestions for Models.py below instead of modifying the code directly.

By using properties we can make definitions much simpler and avoid the need to define methods like `__set_parameter_variation()`, like so:

```python
class Parameter():

    def __init__(self, name, value, prior=None):
        self.name = name
        self._value = value
        self._prior = prior

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, value):
        """This allows setting the value on every MCMC evaluation"""
        self._value = value

    @property
    def prior(self):
        if self._prior is None:
            # set a fixed prior by setting Prior.funcform to a float
            self._prior = Prior(self.value)
        return self._prior

    @prior.setter
    def prior(self, prior):
        if prior is None:
            # set a fixed prior by setting Prior.funcform to a float
            self._prior = Prior(self.value)
        else:
            self._prior = prior

    def is_fixed(self):
        return self.prior.is_fixed()


class Prior():

    def __init__(self, funcform, priormin=-np.inf, priormax=-np.inf):
        # I inverted the order of the arguments since for some functional forms it
        # may not be necessary to define a (min,max) range, such as in a Gaussian
        # (because the integral is finite) or a fixed value.
        # ...

    def is_fixed(self):
        # there may be a better way to test it but you get the point
        return isinstance(self.funcform, float)
        # alternative: return (priormin == priormax)
```

Finally, we could have the prior of a given parameter not be modifiable once it is initialized by removing its setter, but I think the implementation above would eventually allow for the hierarchical inference that @anjavdl was talking about, if I understood it correctly (i.e., the prior is updated as the model is evaluated).

Analogous suggestions apply to the Model class, of course.

I feel like we also need to allow for a parameter to be a function name or something like that, though I'm not sure exactly how. How do we intend the Model structure to allow the user to choose between different mass-observable relations, for instance?

(I believe the convention is for file names to always be lower case.)

**Comment by cristobal-sifon** [comment]
I thought we'd want to go updating the Parameter object during the chain. Perhaps you thought we'd just initialize it when defining the model and then just update with attributes like `median` and `stderr` at write-out? In that case it might make sense to follow your idea (still defining properties)

**Comment by cavestruz** [comment]
Creating tests for *just* the Model supereclass:
- test input types to constructor (func, ind_var, params)

**Comment by matthewkirby** [comment]
We merged into master. There is an additional issue to make this content a little nicer looking but that is beyond the scope of the workshop.
