### ISSUE TITLE
Interface Models superclass with Profiles

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#16]

**Comment by cavestruz** [comment]
- [ ] Pull master into this branch
- [ ] Move sigma crit calculations (and beta calculations) into summarize submodule

**Comment by cristobal-sifon** [comment]
so I wrote a pretty neat (in my opinion anyway) `Profile` object that can be used to construct any particular profile and includes numerical integration of the surface density profile and so on, if necessary. There are a few examples and timing and accuracy tests. There are also other lensing-related things that may be ignored (or not).

https://github.com/cristobal-sifon/astro/blob/master/astro/clusters/lensing_ingredients.ipynb

**Comment by cavestruz** [comment]
@cristobal-sifon - Awesome!  Thanks so much.  I'm tagging @matthewwf2001, @mchoi8739, @matthewkirby, and @brandynlee who were working on profile related code in the repo.  It would be great to integrate some or all of this functionality.

**Comment by aimalz** [comment]
This is now out of scope.

**Comment by matthewkirby** [comment]
Following closing the issue, we are also deleting the branch for this issue since it is no longer relevant. 

@matthewwf2001 this was your branch and @cristobal-sifon you put some effort in here as well, we still value your work! If you wish to continue your involvement we should look at more up to date issues.
