### ISSUE TITLE
Ensure stability of example notebooks (and therefore documentation)

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#242]
The two example notebooks generate a galaxy catalog using `mock_data.py`. At the moment there's no option to define a seed for the random number generation so each time an example notebook is played, it gives different results and therefore the documentation slightly changes every time. I think we should
- [x] modify `mock_data.py` to allow for a seed keyword to be passed
- [x] update the notebooks to use a given seed.

**Comment by cristobal-sifon** [comment]
I've implemented random seeds in `example/Example...` in #235 for the time being. Perhaps this is also what you had in mind but I suggest rather than passing it as an argument to each function, to define an attribute of `mock_data` itself, for instance `mock_data.seed`, or a method `mock_data.set_seed(seed)`. This has the advantage that the user only needs to specify it once in their code rather than on every call (then, say, a value of `None` would set no seed).

**Comment by combet** [comment]
Great thanks ! This nicely solves the problem of #235... I hadn't looked at how to do it and hadn't  realized this could simply be done directly at the notebook level. As for having it in `mock_data`, I'm not sure now this is entirely necessary.

**Comment by cavestruz** [comment]
Note:  WHen you write a notebook, and use random generation, need to define a seed!
