### ISSUE TITLE
Check and solve commented tests in test_polaraveraging

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#260]
There are a bunch of commented out tests in the `test_polaraveraging.py` saying that these rais a warning when running pytest. This should be understood and/or corrected/cleaned out accordingly. (First mentioned in #164).

**Comment by pennalima** [comment]
## utils.py

- Function compute_radial_averages: the standard deviation of the mean was ill-defined, it lead to a division by zero for empty bins. Solution implemented in this branch: each empty bin has its weight set to one.

## test_polaraveraging.py

1) Removed the tests named "Some additional edge cases" because they were failing  since the variable TOLERANCE was missing, and just below there are the same edges tests.
2) Removed the test of the function compute_lensing_angles_flatsky when RA_s = DEC_s = 0.0.The angular separation in this example is > 1. It is not necessary to use this function here. There is already another test checking if the warning for ang. separation > 1 is thrown. 
3) Removed the test for RA_s = RA_l, DEC_s = DEC_l. As it was commented, this is not an error.
4) Test: "Failure when lens and a source share an RA and a DEC". This was not working because the function arctan2(y,x) does not necessarily returns zero when x=y=0. From the manual:
  - If y is +0 (-0) and x is -0, +pi (-pi) is returned.
  - If y is +0 (-0) and x is +0, +0 (-0) is returned. 
To work around this phi is set to zero when angsep == 0. This modification was done in _compute_lensing_angles_flatsky. 
5) When the angular separation RA_s - RA_l is n*2*pi + epsilon, the function  _compute_lensing_angles_flatsky was resulting in a large deltax, this was due the
fact that it was computed  (RA_s - RA_l)*cos(dec_l) and then setting it to (-pi,pi).
Now it computes (RA_s - RA_l) and sets it to be in (-pi,pi) and then multiply
the result by cos(dec_l).
6) Updated the tests checking the case RA_s - RA_l is n*2*pi + epsilon and removed unnecessary ones.

Please check if all these points make sense to you.

**Comment by combet** [comment]
This has been merged - closing issue.

**Comment by combet** [comment]
This has been merged - closing issue
