### ISSUE TITLE
Update misc_sims_examples

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#279]
The examples in misc_sims_examples are outdated and need to be updated.
This is what needs to be done:

- [ ] Check if it will be included in v1.0
  - [x] Contact J. Hollowed to check if new maps are available
  - [ ] Check the estimated time for the fix
- [ ] Replace old functions

**Comment by cavestruz** [comment]
- [ ] Old functions need to be replaced

**Comment by combet** [comment]
This notebook is very obsolete and pointing towards the first high res maps Joe produced and that had problems (I don't remember the specific but I think there was barely any WL signal in them because of a bug). So I'm not sure this example should be part of the v1 release (unless updated maps become available before then).

**Comment by aimalz** [comment]
Since these are no longer included in the master branch at all, I'm going to close this issue. (If I'm mistaken, please feel free to reopen this issue!)
