### ISSUE TITLE
Notebooks to make all figures in the paper and demonstrate API

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#335]
Make a notebook with the exact content shown in the API section of the paper. This way we can assure the API demonstration content in the paper is correct.

**Comment by shenmingfu** [comment]
Maybe we can start from https://github.com/LSSTDESC/CLMM/blob/master/examples/Example1_Fit_Halo_Mass_to_Shear_Catalog.ipynb

We can show code starting from line "cl = clmm.GalaxyCluster.load('mock_GC.pkl')".

The idea is to show that 
1) given a catalog (the user needs to first convert the input catalog into a `GalaxyCluster` object using `clmm.GalaxyCluster`), and then
2) what CLMM can do -- e.g. compute and plot a shear profile and make a mass fitting.

**Comment by shenmingfu** [comment]
I'm testing this notebook on NERSC and using cluster_toolkit backend. When I set random seed to 13 in the notebook section 1.1, I noticed `ValueError: shape mismatch: value array of shape (1,68) could not be broadcast to indexing result of shape (1,)`, which might be caused by bad galaxies. For other random seeds, the results looked fine.
