### ISSUE TITLE
galaxycluster object outline

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#4]
This class should define an object whose attributes are data.  Model methods will perform operations on this data via the entire galaxycluster object.

**Comment by cristobal-sifon** [comment]
I feel like we should rename `GalaxyCluster` to `Lens` or `LensObject`, `LensHalo`, or something similar, but more general than just a galaxy cluster. Maybe even `TestObject`, as this set of operations (binning shapes of objects around a test object) can be used for more applications than just cluster lensing, among which galaxy-galaxy lensing and intrinsic alignments (the latter is the reason why I came up with a name that does not include Lens). We can always have an attribute `object_type` which specifies that a given object is (say) a galaxy cluster, but I'm not sure this would be very useful.

**Comment by cavestruz** [comment]
Hi @cristobal-sifon - @aimalz put together a code structure outline: https://docs.google.com/drawings/d/17PSr9MXRGO0ODjPb5vBVNF4qg3uSbn-1-HbkZdXK5LI/edit?usp=sharing

We're thinking something more generic can take in a GalaxyCluster object, and would be an extension in the future.  (We're ducking out for lunch in the next ~1hr, but feel free to assign yourself to issues or create any other issues.)

**Comment by cristobal-sifon** [comment]
I actually feel there isn't much point in having a `GalaxyCluster` object at all (not with that name, I mean). After all, a galaxy cluster is just any lens but we have certain prior belief about its density profile and so on. And especially given that these prior beliefs are being defined outside the GalaxyCluster object, then GalaxyCluster is just an object around which to azimuthally average galaxy shapes. All lens modeling regarding any kind of object will always follow these steps.

If GalaxyCluster is a subclass of, say, a LensObject super class, what would GalaxyCluster have that the generic LensObject would not have? Please tell me if I'm wrong, but my guess is nothing. A name, at most (since we wouldn't give a name to every galaxy in a GGL analysis). But that can just be an attribute of LensObject that is set to `None` by default and set to something different if found in whatever configuration leads to initializing a LensObject.

So all I'm proposing is that instead of GalaxyCluster and ClusterEnsemble we have LensObject and LensSample or similar, to avoid giving the impression that the code is more limited than it really is.

**Comment by cavestruz** [comment]
Hi @cristobal-sifon - thanks for bringing this up.  So, I think for a GalaxyCluster object, we will want to for instance include information on centering (e.g. if we choose to perturb the center to test the systematics in simulations, or if we want to either marginalize over how miscentered it is or fit for the best center, etc.)   Other lens objects likely have things that expand the scope of the GalaxyCluster class in and of itself.

**Comment by cristobal-sifon** [comment]
Fair enough. I'm sure you've been discussing this enough, so I'll follow along with the GalaxyCluster object :wink:

**Comment by anjavdl** [comment]
Hi @cristobal-sifon , sorry for chiming in late.  My assumption is that GGL will use the two-point machinery developed for cosmic shear and LSS.  For CLMM, we want to keep things general enough to be able to vary the center in case we ever want to (e.g. optical vs. SZ centers, actual fitting for the lensing center, ...).
