### ISSUE TITLE
Update Numcosmo requirement

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#554]
Numcosmo requirement has been fixed to version `0.15.4` on PR #553 as it is breaking with the current numpy version. Motive must be investigated

**Comment by m-aguena** [comment]
@vitenti @pennalima any insights on this?

**Comment by vitenti** [comment]
In the previous version of NumCosmo the power-spectrum was inheriting the default k-interval from the base class. However, this interval was a smaller than necessary for some computations. We modified the default interval for *all* linear matter power spectra, since now the interval is larger then sigma8 is being computed with more precision and that is the reason for the current mismatch (the benchmark power spectrum CLMM uses was computed with the older version of NumCosmo). You can update the benchmark file or reset the object to the old interval.

If you choose to maintain the same benchmark you just need to set the older interval in clmm/cosmology/numcosmo.py, i.e.,
```
    def _eval_linear_matter_powerspectrum(self, k_vals, redshift):

        # Using the EH transfer function as this is the 
        # default for the CCL backend as well
        ps = Nc.PowspecMLTransfer.new (Nc.TransferFuncEH.new()) 
        ps.set_kmin(1.0e-5)
        ps.set_kmax(1.0)
```

Also I noticed the CLMM instantiate a Filter just to compute $\sigma_8$. In this case it is usually cheaper to call: `ps.sigma_tophat_R(self.be_cosmo,1.0e-11,0.0,8.0/self.be_cosmo.h())` with the appropriated relative tolerance (in this call it is 1.0e-11).

**Comment by m-aguena** [comment]
> In the previous version of NumCosmo the power-spectrum was inheriting the default k-interval from the base class. However, this interval was a smaller than necessary for some computations. We modified the default interval for _all_ linear matter power spectra, since now the interval is larger then σ8 is being computed with more precision and that is the reason for the current mismatch (the benchmark power spectrum CLMM uses was computed with the older version of NumCosmo). You can update the benchmark file or reset the object to the old interval.
> 
> If you choose to maintain the same benchmark you just need to set the older interval in clmm/cosmology/numcosmo.py, i.e.,
> 
> ```
>     def _eval_linear_matter_powerspectrum(self, k_vals, redshift):
> 
>         # Using the EH transfer function as this is the 
>         # default for the CCL backend as well
>         ps = Nc.PowspecMLTransfer.new (Nc.TransferFuncEH.new()) 
>         ps.set_kmin(1.0e-5)
>         ps.set_kmax(1.0)
> ```
> 
> Also I noticed the CLMM instantiate a Filter just to compute σ8. In this case it is usually cheaper to call: `ps.sigma_tophat_R(self.be_cosmo,1.0e-11,0.0,8.0/self.be_cosmo.h())` with the appropriated relative tolerance (in this call it is 10−11).

Thanks @vitenti ! What is the `0.0` value in `ps.sigma_tophat_R(self.be_cosmo,1.0e-11,0.0,8.0/self.be_cosmo.h())`? I would like to not have anything hardcoded.

**Comment by vitenti** [comment]
It's the redshift.
