### ISSUE TITLE
Add more flexibility to the cluster ensemble object

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#565]
At the moment, a cluster ensemble object is instantiated from a list of GalaxyCluster objects, that each have a background galaxy catalog attached to them. It then computes the individual profiles and weights and store the results in the cluster ensemble. But the cluster object list means we quickly run into memory issues as @eduardojsbarroso encountered.

We should also support the option where the individual profiles and weights are already available in the GalaxyCluster object and simply used to fill in the cluster ensemble.

Another possibility could be to provide a list of GC object .pkl file names, that would have been previously saved, then have the cluster ensemble loop over those. That way we avoid having to keep in memory N x galaxy catalogs at the same time. 

Need to discuss what is the best approach... @m-aguena

**Comment by eduardojsbarroso** [comment]
Since I need this feature for an analysis, I just copied the `clusterensemble.py` file, deleted the `gclist` from the `__init__` and I call the `add_value` method for each cluster that I have. This could be an easy solution.

 We can make `gc_list == Optional`, and if we instantiate the `ClusterEnsemble` class with no list, the users should call themselves the `add_value` method instead of it being called in the init function. 

This is an option, but we can also go with the way Céline mentioned,  where the user just gives the list of the weights and the `add_value` method does not need to be called at all.

**Comment by combet** [comment]
Thanks @eduardojsbarroso - yes, I totally agree that this is the most straightforward! I'm just wondering whether we should also provide the option were the user had already computed the required quantities. But might be overkill...

**Comment by m-aguena** [comment]
@combet thanks for spotting that. This full computation of the profiles and weights was a temporary implementation, from before GalaxyCluster had weights implemented. There is even a comment written for it. We just have to decide what type of data will be the input.
