### ISSUE TITLE
inferrer class to talk to core/manager

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#68]
We need sufficient code so Manager object in core/manager.py can talk with the inferrer class (e.g. Manager.prepare and Manager.deliver methods, which interact with input/output of inferrer).

**Comment by cavestruz** [comment]
This is related to #Issue/69/manager

**Comment by m-aguena** [comment]
Screenshots of the whiteboard with many schematizations of how the pipeline/inferrer/manager should work [here](https://drive.google.com/file/d/1SqZd2V_j-rYpbZhJDLyXPAcA2H8ZmwEz/view?usp=sharing). Each page is the rearranging of the workflow from different days, so keeps the history of the development and the last page is what you should focus on.

**Comment by aimalz** [comment]
In today's discussion, it sounded like we were going to descope CLMM to not include an inferrer class because making it general enough to be useful would be quite hard.  The idea for a compromise was to instead write some more demos/example notebooks for users to see how CLMM can be used for inference.  If there are no other ideas nor objection, we can close this issue.

**Comment by aimalz** [comment]
This is out of scope.
