### ISSUE TITLE
Help/Advice wanted for PR of branch Issue/67/mock_flexibility

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#79]
Couldn't not complete the PR for Issue/67/mock_flexibility because, I think, Issue/16/ was merged into it at some point. This contains code not ready for Travis and not fully documented yet. Not sure how to revert or proceed. Any help or advice would be very welcome.

**Comment by msimet** [comment]
It looks like Issue 16 wasn't merged in--instead, whoever created Issue/67/mock_flexibility was sitting in Issue/16 when they created the branch (rather than master).  You can see that on the [network visualization page](https://github.com/LSSTDESC/CLMM/network).  So I *think* the following should work:

`git checkout Issue/67/mock_flexibility
git rebase --onto master`

Or, at least, if I try this on my local copy of the repository, the commits from Issue 16 no longer appear when I `git log`.  You might have to do something different when you push to GitHub, but `git push` will probably tell you what to do; if it's something like `--force` then you might want to leave a note on the issue page telling everyone they'll need to pull the branch from GitHub before they make any more changes.

But there might be an easier/better way, of course!  The ways of Git are mysterious.

**Comment by combet** [comment]
Thanks for the feedback. So, yes, clearly I messed it up from the start when I created the branch from Issue 16 instead of master it seems. Didn't know I did that and won't be doing it again :/ 

So I followed @msimet 's advice and rebased the branch to master. I had to `git push --force` it back to the remote and was then able to implement back the small changes we had made to get the extra functionalities we wanted to the mock data. 

`pytest` is running happily on my local machine and github tells me the branch can be merged to master, so I'll open a new PR.
